"""remove_id_from_users

Revision ID: 5e63fa25a2f3
Revises: 45d4ad9a32de
Create Date: 2022-09-26 17:53:19.514875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e63fa25a2f3"
down_revision = "45d4ad9a32de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "id")
    op.create_primary_key(constraint_name="users_pkey", table_name="users", columns=["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_pkey", "users", "primary")
    op.execute('ALTER TABLE "users" ADD COLUMN "id" SERIAL PRIMARY KEY')
    # ### end Alembic commands ###
