"""remove_id_from_recipes

Revision ID: 45d4ad9a32de
Revises: 9f2eba8362ea
Create Date: 2022-09-26 16:38:00.491445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45d4ad9a32de"
down_revision = "9f2eba8362ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "id")
    op.create_primary_key(constraint_name="recipes_pkey", table_name="recipes", columns=["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recipes_pkey", "recipes", "primary")
    op.execute('ALTER TABLE "recipes" ADD COLUMN "id" SERIAL PRIMARY KEY')
    # ### end Alembic commands ###
