name: Run tests on any Push event
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  build:
    runs-on: ubuntu-latest
    container: "python:3.10-slim"
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.5
        # Provide the password for postgres
        env:
          POSTGRES_DB: oipie
          POSTGRES_PASSWORD: password
          POSTGRES_USER: oipie
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: pylint ./src/**/*.py
      - name: Run tests
        run: pytest
        env:
          DATABASE_HOST: postgres
