name: Deploy on heroku
on:
  push:
    branches:
      - "master"
jobs:
  tests:
    runs-on: ubuntu-latest
    container: "python:3.10-slim"
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.5
        # Provide the password for postgres
        env:
          POSTGRES_DB: oipie
          POSTGRES_PASSWORD: password
          POSTGRES_USER: oipie
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: pylint ./src/**/*.py
      - name: Run tests
        run: pytest
        env:
          DATABASE_HOST: postgres
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Install heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push to Heroku
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
