name: Deploy on heroku
on:
  push:
    branches:
      - "dev"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push to Heroku
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
