name: Deploys to main
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push to Heroku
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} --recursive
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Relase last container to Heroku
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
